import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import { HeaderHome } from "@/components/main/header";
import QueryProvider from "@/providers/QueryProviders";
import { Toaster } from "@/components/ui/sonner";
import { HeaderAdmin } from "../../../components/admin/header";
import AuthProvider from "./../../../providers/AuthProviders";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-gewst-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: "%s | BamCargo",
    default: "BAMCARGO | Amanah. Cepat dan Tepat.",
  },
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-50 dark:bg-[#171717]`}
      >
        <AuthProvider>
          <QueryProvider>
            <HeaderAdmin />
            <Toaster richColors theme={"light"} />
            {children}
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
